### ISSUE TITLE
Breaking changes in v2.0.0

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/js-algorand-sdk#650]
Itemizes functionality that will be removed in the upcoming major release.

Task list for algorand-sdk-testing stories:
- [x] https://github.com/algorand/algorand-sdk-testing/issues/201 - https://github.com/algorand/js-algorand-sdk/pull/713
- [x] https://github.com/algorand/algorand-sdk-testing/issues/202 - no need
- [x] https://github.com/algorand/algorand-sdk-testing/issues/223 - https://github.com/algorand/js-algorand-sdk/pull/712
- [x] https://github.com/algorand/algorand-sdk-testing/issues/254 - https://github.com/algorand/js-algorand-sdk/pull/712
- [x] https://github.com/algorand/algorand-sdk-testing/issues/255 - https://github.com/algorand/js-algorand-sdk/pull/714
- [x] https://github.com/algorand/generator/issues/46 - https://github.com/algorand/generator/pull/51
- [x] Regenerate Typescript models via generator - https://github.com/algorand/js-algorand-sdk/pull/720
