### ISSUE TITLE
Finish v3 release

### ISSUE THREAD

**Issue by jasonpaulos** [algorand/js-algorand-sdk#824]
This issue outlines all remaining work that's necessary to release v3 of this library (which is currently in development in #817)

- [ ] Bigints should be used by default for REST API decoding
- [ ] Transaction and related classes must be updated to accept bigints for all numeric fields
- [ ] Remove ability to pass raw objects as transactions to functions (tech debt, and solves #740)
- [ ] Update `BlockHeader` class to have accurate types
- [ ] Look into inline response type support in the REST API
- [ ] Should indexer responses also be typed?
- [ ] Update ESM bundle support to adhere to modern standards (#819). For the time being, we want to continue supporting commonjs and ESM, but our ESM support has fallen behind current practices.
- [x] Update `SourceMap` class to map columns (#834)
- [ ] `EncodedSignedTransaction` is not properly decoded from REST API -- binary fields are typed as `Uint8Array` but left as base64 strings when coming from JSON

#816 has been opened as an attempt to address most of these issues

**Comment by paulmillr** [comment]
Thoughts on the security improvement? https://github.com/algorand/js-algorand-sdk/issues/742
